# Generated by Django 5.0.3 on 2024-08-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mobile_No',
            field=models.ImageField(default='012345678', upload_to=''),
        ),
    ]
